name: ðŸ¤– Dependabot auto-merge

on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  call-auto-merge-workflow:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: cu-cit-cloud-team/reusable-workflows/.github/workflows/dependabot-auto-merge.yml@main
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN}}
